FROM netboxcommunity/netbox:v3.7-2.8.0

COPY django.po /opt/netbox/netbox/translations/en/LC_MESSAGES/django.po
COPY django.mo /opt/netbox/netbox/translations/en/LC_MESSAGES/django.mo
COPY constants.py /opt/netbox/netbox/extras/constants.py 
